export const rainbowlandsCalendar = {
  id: "rainbowlands",
  name: "CALENDARIA.Calendar.rainbowlands.Name",
  description: "CALENDARIA.Calendar.rainbowlands.Description",
  years: {
    yearZero: 0,
    firstWeekday: 0,
    leapYear: null,
    resetWeekdays: false,
    allowNegativeYears: true,
    names: [],
  },
  months: {
    values: {
      0: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Newfirst",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.NewfirstShort",
        days: 31,
        leapDays: null,
        startingWeekday: null,
        ordinal: 1,
      },
      1: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Lastmonth",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.LastmonthShort",
        days: 30,
        leapDays: null,
        startingWeekday: null,
        ordinal: 2,
      },
      2: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Firstmonth",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.FirstmonthShort",
        days: 30,
        leapDays: null,
        startingWeekday: null,
        ordinal: 3,
      },
      3: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Greenmonth",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.GreenmonthShort",
        days: 31,
        leapDays: null,
        startingWeekday: null,
        ordinal: 4,
      },
      4: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Redmonth",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.RedmonthShort",
        days: 30,
        leapDays: null,
        startingWeekday: null,
        ordinal: 5,
      },
      5: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Orangemonth",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.OrangemonthShort",
        days: 30,
        leapDays: null,
        startingWeekday: null,
        ordinal: 6,
      },
      6: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Yellowmonth",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.YellowmonthShort",
        days: 31,
        leapDays: null,
        startingWeekday: null,
        ordinal: 7,
      },
      7: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Oldsecond",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.OldsecondShort",
        days: 30,
        leapDays: null,
        startingWeekday: null,
        ordinal: 8,
      },
      8: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Unity",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.UnityShort",
        days: 30,
        leapDays: null,
        startingWeekday: null,
        ordinal: 9,
      },
      9: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Violetmonth",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.VioletmonthShort",
        days: 31,
        leapDays: null,
        startingWeekday: null,
        ordinal: 10,
      },
      10: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Snowbringer",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.SnowbringerShort",
        days: 30,
        leapDays: null,
        startingWeekday: null,
        ordinal: 11,
      },
      11: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Deadwinter",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.DeadwinterShort",
        days: 30,
        leapDays: null,
        startingWeekday: null,
        ordinal: 12,
      },
    },
  },
  days: {
    values: {
      tYMU6xsaOkeHP11I: {
        ordinal: 1,
        name: "CALENDARIA.Calendar.rainbowlands.Days.Monday",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Days.MondayShort",
        isRestDay: false,
      },
      xKyEcjKKvmV8Fad5: {
        ordinal: 2,
        name: "CALENDARIA.Calendar.rainbowlands.Days.Tuesday",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Days.TuesdayShort",
        isRestDay: false,
      },
      xlO0AvFK5p5IJ1hq: {
        ordinal: 3,
        name: "CALENDARIA.Calendar.rainbowlands.Days.Wednesday",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Days.WednesdayShort",
        isRestDay: false,
      },
      FsTcz2LrjxoCpsMz: {
        ordinal: 4,
        name: "CALENDARIA.Calendar.rainbowlands.Days.Thursday",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Days.ThursdayShort",
        isRestDay: false,
      },
      x5or1qKgxCfVY6AT: {
        ordinal: 5,
        name: "CALENDARIA.Calendar.rainbowlands.Days.Friday",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Days.FridayShort",
        isRestDay: false,
      },
      "2ErBxcJFWHjY1u6e": {
        ordinal: 6,
        name: "CALENDARIA.Calendar.rainbowlands.Days.Saturday",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Days.SaturdayShort",
        isRestDay: true,
      },
      zEDb8A2uOPRo0i2b: {
        ordinal: 7,
        name: "CALENDARIA.Calendar.rainbowlands.Days.Sunday",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Days.SundayShort",
        isRestDay: true,
      },
    },
    daysPerYear: 364,
    hoursPerDay: 24,
    minutesPerHour: 60,
    secondsPerMinute: 60,
  },
  secondsPerRound: 6,
  seasons: {
    type: "dated",
    offset: 0,
    values: {
      0: {
        name: "CALENDARIA.Calendar.rainbowlands.Seasons.Winter",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Seasons.WinterShort",
        icon: "fa-snowflake",
        color: "#87CEEB",
        seasonalType: "winter",
        climate: {
          temperatures: {
            min: -5,
            max: 5,
          },
          presets: {
            cloudy: {
              id: "cloudy",
              chance: 4,
              enabled: true,
            },
            overcast: {
              id: "overcast",
              chance: 4,
              enabled: true,
            },
            drizzle: {
              id: "drizzle",
              chance: 2,
              enabled: true,
            },
            rain: {
              id: "rain",
              chance: 1,
              enabled: true,
            },
            snow: {
              id: "snow",
              chance: 8,
              enabled: true,
            },
            blizzard: {
              id: "blizzard",
              chance: 5,
              enabled: true,
            },
            "ice-storm": {
              id: "ice-storm",
              chance: 5,
            },
            "rolling-fog": {
              id: "rolling-fog",
              chance: 1,
              enabled: true,
            },
            nullfront: {
              id: "nullfront",
              chance: 1,
              enabled: true,
            },
            "permafrost-surge": {
              id: "permafrost-surge",
              chance: 1,
              enabled: true,
            },
            "meteor-shower": {
              id: "meteor-shower",
              chance: 1,
              enabled: true,
            },
          },
        },
        monthStart: 11,
        monthEnd: 1,
        dayStart: 0,
        dayEnd: 29,
      },
      1: {
        name: "CALENDARIA.Calendar.rainbowlands.Seasons.Spring",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Seasons.SpringShort",
        icon: "fa-seedling",
        color: "#90EE90",
        seasonalType: "spring",
        climate: {
          temperatures: {
            min: 8,
            max: 18,
          },
          presets: {
            "partly-cloudy": {
              id: "partly-cloudy",
              chance: 4,
              enabled: true,
            },
            rain: {
              id: "rain",
              chance: 4,
              enabled: true,
            },
            snow: {
              id: "snow",
              chance: 1,
              enabled: true,
            },
            sleet: {
              id: "sleet",
              chance: 4,
              enabled: true,
            },
            "heat-wave": {
              id: "heat-wave",
              chance: 2,
              enabled: true,
            },
            thunderstorm: {
              id: "thunderstorm",
              chance: 4,
              enabled: true,
            },
            monsoon: {
              id: "monsoon",
              chance: 2,
              enabled: true,
            },
            "sakura-bloom": {
              id: "sakura-bloom",
              chance: 2,
              enabled: true,
            },
            "ley-surge": {
              id: "ley-surge",
              chance: 1,
              enabled: true,
            },
            "acid-rain": {
              id: "acid-rain",
              chance: 1,
              enabled: true,
            },
            "blood-rain": {
              id: "blood-rain",
              chance: 1,
              enabled: true,
            },
            "divine-light": {
              id: "divine-light",
              chance: 1,
              enabled: true,
            },
          },
        },
        monthStart: 2,
        monthEnd: 4,
        dayStart: 0,
        dayEnd: 29,
      },
      2: {
        name: "CALENDARIA.Calendar.rainbowlands.Seasons.Summer",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Seasons.SummerShort",
        icon: "fa-sun",
        color: "#FFD700",
        seasonalType: "summer",
        climate: {
          temperatures: {
            min: 18,
            max: 36,
          },
          presets: {
            clear: {
              id: "clear",
              chance: 5,
              enabled: true,
            },
            "partly-cloudy": {
              id: "partly-cloudy",
              chance: 5,
              enabled: true,
            },
            cloudy: {
              id: "cloudy",
              chance: 5,
              enabled: true,
            },
            "heat-wave": {
              id: "heat-wave",
              chance: 5,
              enabled: true,
            },
            thunderstorm: {
              id: "thunderstorm",
              chance: 4,
              enabled: true,
            },
            tornado: {
              id: "tornado",
              chance: 3,
              enabled: true,
            },
            hurricane: {
              id: "hurricane",
              chance: 2,
              enabled: true,
            },
            ashfall: {
              id: "ashfall",
              chance: 1,
              enabled: true,
            },
            sandstorm: {
              id: "sandstorm",
              chance: 2,
              enabled: true,
            },
            "wildfire-smoke": {
              id: "wildfire-smoke",
              chance: 2,
              enabled: true,
            },
            "dust-devil": {
              id: "dust-devil",
              chance: 2,
            },
            "black-sun": {
              id: "black-sun",
              chance: 1,
              enabled: true,
            },
            gravewind: {
              id: "gravewind",
              chance: 1,
              enabled: true,
            },
            "arcane-winds": {
              id: "arcane-winds",
              chance: 1,
              enabled: true,
            },
          },
        },
        monthStart: 5,
        monthEnd: 7,
        dayStart: 0,
        dayEnd: 29,
      },
      3: {
        name: "CALENDARIA.Calendar.rainbowlands.Seasons.Autumn",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Seasons.AutumnShort",
        icon: "fa-leaf",
        color: "#DEB887",
        seasonalType: "autumn",
        climate: {
          temperatures: {
            min: 6,
            max: 20,
          },
          presets: {
            overcast: {
              id: "overcast",
              chance: 5,
              enabled: true,
            },
            drizzle: {
              id: "drizzle",
              chance: 5,
              enabled: true,
            },
            rain: {
              id: "rain",
              chance: 5,
              enabled: true,
            },
            fog: {
              id: "fog",
              chance: 4,
              enabled: true,
            },
            snow: {
              id: "snow",
              chance: 4,
              enabled: true,
            },
            sleet: {
              id: "sleet",
              chance: 5,
            },
            thunderstorm: {
              id: "thunderstorm",
              chance: 4,
              enabled: true,
            },
            blizzard: {
              id: "blizzard",
              chance: 2,
              enabled: true,
            },
            "ice-storm": {
              id: "ice-storm",
              chance: 2,
              enabled: true,
            },
            sandstorm: {
              id: "sandstorm",
              chance: 4,
              enabled: true,
            },
            "rolling-fog": {
              id: "rolling-fog",
              chance: 4,
              enabled: true,
            },
            "aether-haze": {
              id: "aether-haze",
              chance: 1,
              enabled: true,
            },
            "permafrost-surge": {
              id: "permafrost-surge",
              chance: 1,
              enabled: true,
            },
            gravewind: {
              id: "gravewind",
              chance: 1,
              enabled: true,
            },
            veilfall: {
              id: "veilfall",
              chance: 1,
              enabled: true,
            },
            "acid-rain": {
              id: "acid-rain",
              chance: 2,
              enabled: true,
            },
          },
        },
        monthStart: 8,
        monthEnd: 10,
        dayStart: 0,
        dayEnd: 29,
      },
    },
  },
  eras: {},
  festivals: {},
  moons: {},
  cycles: {},
  canonicalHours: {},
  weeks: {
    enabled: true,
    type: "year-based",
    names: {
      k4BbAoQlEERpoA4U: {
        name: "Week 1",
        abbreviation: "Wk 1",
        weekNumber: 1,
      },
      GhRqPTEGteQFWL0C: {
        name: "Week 2",
        abbreviation: "Wk 2",
        weekNumber: 2,
      },
      "8EBnfHPUZacIHNS1": {
        name: "Week 3",
        abbreviation: "Wk 3",
        weekNumber: 3,
      },
      FtBM23LmPd3QgGjB: {
        name: "Week 4",
        abbreviation: "Wk 4",
        weekNumber: 4,
      },
      lYDfmr6XhUgcXN4D: {
        name: "Week 5",
        abbreviation: "Wk 5",
        weekNumber: 5,
      },
      jkNBkUCJK6uO8P3S: {
        name: "Week 6",
        abbreviation: "Wk 6",
        weekNumber: 6,
      },
      TGgs2450ky14JUtM: {
        name: "Week 7",
        abbreviation: "Wk 7",
        weekNumber: 7,
      },
      tNJf8D27MUoOsptp: {
        name: "Week 8",
        abbreviation: "Wk 8",
        weekNumber: 8,
      },
      CE4YEFoPDRH7legY: {
        name: "Week 9",
        abbreviation: "Wk 9",
        weekNumber: 9,
      },
      pjyDzSfPH90Ox5lz: {
        name: "Week 10",
        abbreviation: "Wk 10",
        weekNumber: 10,
      },
      cOA9XBEqDSrd5MPh: {
        name: "Week 11",
        abbreviation: "Wk 11",
        weekNumber: 11,
      },
      "2k6rzDSpLq8DVY41": {
        name: "Week 12",
        abbreviation: "Wk 12",
        weekNumber: 12,
      },
      bHBcdbQEK9rfg6BK: {
        name: "Week 13",
        abbreviation: "Wk 13",
        weekNumber: 13,
      },
    },
  },
  amPmNotation: {
    am: "AM",
    pm: "PM",
    amAbbr: "AM",
    pmAbbr: "PM",
  },
  dateFormats: {
    short: "{{EE}}, {{MMM}} {{DD}}",
    long: "{{EEEE}}, {{MMMM}} {{DD}}, {{YY}}",
    full: "{{EEEE}}, {{MMMM}} {{DD}}, {{YYYY}}",
    time: "{{H}}:{{M}}",
    time12: "{{h}}:{{M}} {{p}}",
    weekHeader: "[namedWeek] {{QQQQ}}",
    yearHeader: "Y",
    yearLabel: "YYYY",
  },
  metadata: {
    id: "rainbowlands",
    description: "CALENDARIA.Calendar.rainbowlands.Description",
    author: "Luber",
    system: "sdm",
    exportedFrom: "calendaria",
    exportedAt: 1775902199962,
    version: "1.0.4",
  },
  weather: {
    activeZone: "temperate",
    zones: {},
  },
  leapYearConfig: null,
  daylight: {
    enabled: false,
    shortestDay: 8,
    longestDay: 16,
    winterSolstice: 0,
    summerSolstice: 182,
  },
  currentDate: {
    year: 1,
    month: 0,
    day: 1,
    dayOfMonth: 1,
    hour: 12,
    minute: 0,
  },
  cycleFormat: "",
};
