export const rainbowlandsCalendar = {
  id: "rainbowlands",
  name: "CALENDARIA.Calendar.rainbowlands.Name",
  description: "CALENDARIA.Calendar.rainbowlands.Description",
  years: {
    yearZero: 0,
    firstWeekday: 0,
    leapYear: null,
    resetWeekdays: false,
    allowNegativeYears: true,
    names: [],
  },
  months: {
    values: {
      0: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Newfirst",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.NewfirstShort",
        days: 31,
        leapDays: null,
        startingWeekday: null,
        ordinal: 1,
      },
      1: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Lastmonth",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.LastmonthShort",
        days: 30,
        leapDays: null,
        startingWeekday: null,
        ordinal: 2,
      },
      2: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Firstmonth",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.FirstmonthShort",
        days: 30,
        leapDays: null,
        startingWeekday: null,
        ordinal: 3,
      },
      3: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Greenmonth",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.GreenmonthShort",
        days: 31,
        leapDays: null,
        startingWeekday: null,
        ordinal: 4,
      },
      4: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Redmonth",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.RedmonthShort",
        days: 30,
        leapDays: null,
        startingWeekday: null,
        ordinal: 5,
      },
      5: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Orangemonth",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.OrangemonthShort",
        days: 30,
        leapDays: null,
        startingWeekday: null,
        ordinal: 6,
      },
      6: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Yellowmonth",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.YellowmonthShort",
        days: 31,
        leapDays: null,
        startingWeekday: null,
        ordinal: 7,
      },
      7: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Oldsecond",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.OldsecondShort",
        days: 30,
        leapDays: null,
        startingWeekday: null,
        ordinal: 8,
      },
      8: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Unity",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.UnityShort",
        days: 30,
        leapDays: null,
        startingWeekday: null,
        ordinal: 9,
      },
      9: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Violetmonth",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.VioletmonthShort",
        days: 31,
        leapDays: null,
        startingWeekday: null,
        ordinal: 10,
      },
      10: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Snowbringer",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.SnowbringerShort",
        days: 30,
        leapDays: null,
        startingWeekday: null,
        ordinal: 11,
      },
      11: {
        name: "CALENDARIA.Calendar.rainbowlands.Month.Deadwinter",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Month.DeadwinterShort",
        days: 30,
        leapDays: null,
        startingWeekday: null,
        ordinal: 12,
      },
    },
  },
  days: {
    values: {
      tYMU6xsaOkeHP11I: {
        ordinal: 1,
        name: "CALENDARIA.Calendar.rainbowlands.Days.Monday",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Days.MondayShort",
        isRestDay: false,
      },
      xKyEcjKKvmV8Fad5: {
        ordinal: 2,
        name: "CALENDARIA.Calendar.rainbowlands.Days.Tuesday",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Days.TuesdayShort",
        isRestDay: false,
      },
      xlO0AvFK5p5IJ1hq: {
        ordinal: 3,
        name: "CALENDARIA.Calendar.rainbowlands.Days.Wednesday",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Days.WednesdayShort",
        isRestDay: false,
      },
      FsTcz2LrjxoCpsMz: {
        ordinal: 4,
        name: "CALENDARIA.Calendar.rainbowlands.Days.Thursday",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Days.ThursdayShort",
        isRestDay: false,
      },
      x5or1qKgxCfVY6AT: {
        ordinal: 5,
        name: "CALENDARIA.Calendar.rainbowlands.Days.Friday",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Days.FridayShort",
        isRestDay: false,
      },
      "2ErBxcJFWHjY1u6e": {
        ordinal: 6,
        name: "CALENDARIA.Calendar.rainbowlands.Days.Saturday",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Days.SaturdayShort",
        isRestDay: true,
      },
      zEDb8A2uOPRo0i2b: {
        ordinal: 7,
        name: "CALENDARIA.Calendar.rainbowlands.Days.Sunday",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Days.SundayShort",
        isRestDay: true,
      },
    },
    daysPerYear: 364,
    hoursPerDay: 24,
    minutesPerHour: 60,
    secondsPerMinute: 60,
  },
  secondsPerRound: 6,
  seasons: {
    type: "dated",
    offset: 0,
    values: {
      1: {
        name: "CALENDARIA.Calendar.rainbowlands.Seasons.Winter1",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Seasons.WinterShort",
        icon: "fa-snowflake",
        color: "#87CEEB",
        seasonalType: "winter",
        climate: {
          temperatures: { min: -5, max: 5 },
          presets: {
            "partly-cloudy": { id: "partly-cloudy", chance: 1, enabled: true },
            cloudy: { id: "cloudy", chance: 4, enabled: true },
            overcast: { id: "overcast", chance: 12, enabled: true },
            snow: { id: "snow", chance: 14, enabled: true },
            blizzard: { id: "blizzard", chance: 20, enabled: true },
            "ice-storm": { id: "ice-storm", chance: 16, enabled: true },
            "permafrost-surge": {
              id: "permafrost-surge",
              chance: 2,
              enabled: true,
            },
            nullfront: { id: "nullfront", chance: 1, enabled: true },
          },
        },
        monthStart: 0,
        monthEnd: 0,
        dayStart: 0,
        dayEnd: 30,
      },
      2: {
        name: "CALENDARIA.Calendar.rainbowlands.Seasons.Winter2",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Seasons.WinterShort",
        icon: "fa-snowflake",
        color: "#87CEEB",
        seasonalType: "winter",
        climate: {
          temperatures: { min: 0, max: 8 },
          presets: {
            "partly-cloudy": { id: "partly-cloudy", chance: 2, enabled: true },
            cloudy: { id: "cloudy", chance: 6, enabled: true },
            overcast: { id: "overcast", chance: 12, enabled: true },
            drizzle: { id: "drizzle", chance: 4, enabled: true },
            rain: { id: "rain", chance: 4, enabled: true },
            snow: { id: "snow", chance: 16, enabled: true },
            blizzard: { id: "blizzard", chance: 20, enabled: true },
            "ice-storm": { id: "ice-storm", chance: 10, enabled: true },
            "rolling-fog": { id: "rolling-fog", chance: 3, enabled: true },
            "meteor-shower": { id: "meteor-shower", chance: 2, enabled: true },
          },
        },
        monthStart: 1,
        monthEnd: 1,
        dayStart: 0,
        dayEnd: 29,
      },
      3: {
        name: "CALENDARIA.Calendar.rainbowlands.Seasons.Spring3",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Seasons.SpringShort",
        icon: "fa-seedling",
        color: "#90EE90",
        seasonalType: "spring",
        climate: {
          temperatures: { min: 3, max: 18 },
          presets: {
            clear: { id: "clear", chance: 8, enabled: true },
            cloudy: { id: "cloudy", chance: 10, enabled: true },
            overcast: { id: "overcast", chance: 12, enabled: true },
            drizzle: { id: "drizzle", chance: 15, enabled: true },
            rain: { id: "rain", chance: 20, enabled: true },
            snow: { id: "snow", chance: 8, enabled: true },
            sleet: { id: "sleet", chance: 10, enabled: true },
            monsoon: { id: "monsoon", chance: 8, enabled: true },
            thunderstorm: { id: "thunderstorm", chance: 6, enabled: true },
            "acid-rain": { id: "acid-rain", chance: 2, enabled: true },
            "blood-rain": { id: "blood-rain", chance: 2, enabled: true },
          },
        },
        monthStart: 2,
        monthEnd: 2,
        dayStart: 0,
        dayEnd: 29,
      },
      4: {
        name: "CALENDARIA.Calendar.rainbowlands.Seasons.Spring4",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Seasons.SpringShort",
        icon: "fa-seedling",
        color: "#90EE90",
        seasonalType: "spring",
        climate: {
          temperatures: { min: 8, max: 18 },
          presets: {
            clear: { id: "clear", chance: 10, enabled: true },
            "partly-cloudy": { id: "partly-cloudy", chance: 12, enabled: true },
            cloudy: { id: "cloudy", chance: 12, enabled: true },
            overcast: { id: "overcast", chance: 10, enabled: true },
            drizzle: { id: "drizzle", chance: 16, enabled: true },
            rain: { id: "rain", chance: 20, enabled: true },
            "heat-wave": { id: "heat-wave", chance: 6, enabled: true },
            thunderstorm: { id: "thunderstorm", chance: 8, enabled: true },
            "ley-surge": { id: "ley-surge", chance: 2, enabled: true },
          },
        },
        monthStart: 3,
        monthEnd: 3,
        dayStart: 0,
        dayEnd: 30,
      },
      5: {
        name: "CALENDARIA.Calendar.rainbowlands.Seasons.Spring5",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Seasons.SpringShort",
        icon: "fa-seedling",
        color: "#90EE90",
        seasonalType: "spring",
        climate: {
          temperatures: { min: 8, max: 20 },
          presets: {
            clear: { id: "clear", chance: 10, enabled: true },
            "partly-cloudy": { id: "partly-cloudy", chance: 10, enabled: true },
            cloudy: { id: "cloudy", chance: 10, enabled: true },
            overcast: { id: "overcast", chance: 8, enabled: true },
            drizzle: { id: "drizzle", chance: 12, enabled: true },
            rain: { id: "rain", chance: 16, enabled: true },
            thunderstorm: { id: "thunderstorm", chance: 20, enabled: true },
            monsoon: { id: "monsoon", chance: 14, enabled: true },
            "heat-wave": { id: "heat-wave", chance: 10, enabled: true },
            "sakura-bloom": { id: "sakura-bloom", chance: 4, enabled: true },
            "divine-light": { id: "divine-light", chance: 2, enabled: true },
          },
        },
        monthStart: 4,
        monthEnd: 4,
        dayStart: 0,
        dayEnd: 29,
      },
      6: {
        name: "CALENDARIA.Calendar.rainbowlands.Seasons.Summer6",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Seasons.SummerShort",
        icon: "fa-sun",
        color: "#FFD700",
        seasonalType: "summer",
        climate: {
          temperatures: { min: 15, max: 25 },
          presets: {
            clear: { id: "clear", chance: 20, enabled: true },
            "partly-cloudy": { id: "partly-cloudy", chance: 14, enabled: true },
            cloudy: { id: "cloudy", chance: 4, enabled: true },
            "heat-wave": { id: "heat-wave", chance: 18, enabled: true },
            sandstorm: { id: "sandstorm", chance: 8, enabled: true },
            "dust-devil": { id: "dust-devil", chance: 5, enabled: true },
            "black-sun": { id: "black-sun", chance: 2, enabled: true },
          },
        },
        monthStart: 5,
        monthEnd: 5,
        dayStart: 0,
        dayEnd: 29,
      },
      7: {
        name: "CALENDARIA.Calendar.rainbowlands.Seasons.Summer7",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Seasons.SummerShort",
        icon: "fa-sun",
        color: "#FFD700",
        seasonalType: "summer",
        climate: {
          temperatures: { min: 18, max: 36 },
          presets: {
            clear: { id: "clear", chance: 18, enabled: true },
            "partly-cloudy": { id: "partly-cloudy", chance: 12, enabled: true },
            "heat-wave": { id: "heat-wave", chance: 20, enabled: true },
            "wildfire-smoke": {
              id: "wildfire-smoke",
              chance: 8,
              enabled: true,
            },
            ashfall: { id: "ashfall", chance: 4, enabled: true },
            "dust-devil": { id: "dust-devil", chance: 4, enabled: true },
          },
        },
        monthStart: 6,
        monthEnd: 6,
        dayStart: 0,
        dayEnd: 30,
      },
      8: {
        name: "CALENDARIA.Calendar.rainbowlands.Seasons.Summer8",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Seasons.SummerShort",
        icon: "fa-sun",
        color: "#FFD700",
        seasonalType: "summer",
        climate: {
          temperatures: { min: 15, max: 29 },
          presets: {
            clear: { id: "clear", chance: 8, enabled: true },
            "partly-cloudy": { id: "partly-cloudy", chance: 10, enabled: true },
            cloudy: { id: "cloudy", chance: 8, enabled: true },
            overcast: { id: "overcast", chance: 6, enabled: true },
            drizzle: { id: "drizzle", chance: 6, enabled: true },
            rain: { id: "rain", chance: 12, enabled: true },
            thunderstorm: { id: "thunderstorm", chance: 20, enabled: true },
            tornado: { id: "tornado", chance: 10, enabled: true },
            hurricane: { id: "hurricane", chance: 6, enabled: true },
            "heat-wave": { id: "heat-wave", chance: 14, enabled: true },
            "arcane-winds": { id: "arcane-winds", chance: 2, enabled: true },
            gravewind: { id: "gravewind", chance: 2, enabled: true },
          },
        },
        monthStart: 7,
        monthEnd: 7,
        dayStart: 0,
        dayEnd: 29,
      },
      9: {
        name: "CALENDARIA.Calendar.rainbowlands.Seasons.Autumn9",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Seasons.AutumnShort",
        icon: "fa-leaf",
        color: "#DEB887",
        seasonalType: "autumn",
        climate: {
          temperatures: { min: 10, max: 20 },
          presets: {
            clear: { id: "clear", chance: 8, enabled: true },
            overcast: { id: "overcast", chance: 10, enabled: true },
            drizzle: { id: "drizzle", chance: 12, enabled: true },
            rain: { id: "rain", chance: 20, enabled: true },
            thunderstorm: { id: "thunderstorm", chance: 16, enabled: true },
            monsoon: { id: "monsoon", chance: 14, enabled: true },
            "acid-rain": { id: "acid-rain", chance: 6, enabled: true },
          },
        },
        monthStart: 8,
        monthEnd: 8,
        dayStart: 0,
        dayEnd: 29,
      },
      10: {
        name: "CALENDARIA.Calendar.rainbowlands.Seasons.Autumn10",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Seasons.AutumnShort",
        icon: "fa-leaf",
        color: "#DEB887",
        seasonalType: "autumn",
        climate: {
          temperatures: { min: 4, max: 17 },
          presets: {
            clear: { id: "clear", chance: 8, enabled: true },
            cloudy: { id: "cloudy", chance: 12, enabled: true },
            overcast: { id: "overcast", chance: 14, enabled: true },
            drizzle: { id: "drizzle", chance: 10, enabled: true },
            rain: { id: "rain", chance: 16, enabled: true },
            snow: { id: "snow", chance: 14, enabled: true },
            sleet: { id: "sleet", chance: 10, enabled: true },
            blizzard: { id: "blizzard", chance: 8, enabled: true },
            fog: { id: "fog", chance: 12, enabled: true },
            "rolling-fog": { id: "rolling-fog", chance: 10, enabled: true },
            sandstorm: { id: "sandstorm", chance: 6, enabled: true },
            veilfall: { id: "veilfall", chance: 2, enabled: true },
            "aether-haze": { id: "aether-haze", chance: 2, enabled: true },
          },
        },
        monthStart: 9,
        monthEnd: 9,
        dayStart: 0,
        dayEnd: 30,
      },
      11: {
        name: "CALENDARIA.Calendar.rainbowlands.Seasons.Autumn11",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Seasons.AutumnShort",
        icon: "fa-leaf",
        color: "#DEB887",
        seasonalType: "autumn",
        climate: {
          temperatures: { min: 4, max: 10 },
          presets: {
            clear: { id: "clear", chance: 6, enabled: true },
            cloudy: { id: "cloudy", chance: 8, enabled: true },
            overcast: { id: "overcast", chance: 14, enabled: true },
            snow: { id: "snow", chance: 16, enabled: true },
            blizzard: { id: "blizzard", chance: 18, enabled: true },
            "ice-storm": { id: "ice-storm", chance: 16, enabled: true },
            windy: { id: "windy", chance: 10, enabled: true },
            "permafrost-surge": {
              id: "permafrost-surge",
              chance: 4,
              enabled: true,
            },
            gravewind: { id: "gravewind", chance: 3, enabled: true },
          },
        },
        monthStart: 10,
        monthEnd: 10,
        dayStart: 0,
        dayEnd: 29,
      },
      12: {
        name: "CALENDARIA.Calendar.rainbowlands.Seasons.Winter12",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Seasons.WinterShort",
        icon: "fa-snowflake",
        color: "#87CEEB",
        seasonalType: "winter",
        climate: {
          temperatures: { min: -2, max: 5 },
          presets: {
            overcast: { id: "overcast", chance: 8, enabled: true },
            snow: { id: "snow", chance: 14, enabled: true },
            blizzard: { id: "blizzard", chance: 20, enabled: true },
            "ice-storm": { id: "ice-storm", chance: 14, enabled: true },
            nullfront: { id: "nullfront", chance: 4, enabled: true },
            "permafrost-surge": {
              id: "permafrost-surge",
              chance: 3,
              enabled: true,
            },
          },
        },
        monthStart: 11,
        monthEnd: 11,
        dayStart: 0,
        dayEnd: 29,
      },
    },
  },
  eras: {},
  festivals: {},
  moons: {},
  cycles: {},
  canonicalHours: {},
  weeks: {
    enabled: true,
    type: "year-based",
    repeat: true,
    names: {
      k4BbAoQlEERpoA4U: {
        name: "CALENDARIA.Calendar.rainbowlands.Weeks.1",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Weeks.1Short",
        weekNumber: 1,
      },
      GhRqPTEGteQFWL0C: {
        name: "CALENDARIA.Calendar.rainbowlands.Weeks.2",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Weeks.2Short",
        weekNumber: 2,
      },
      "8EBnfHPUZacIHNS1": {
        name: "CALENDARIA.Calendar.rainbowlands.Weeks.3",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Weeks.3Short",
        weekNumber: 3,
      },
      FtBM23LmPd3QgGjB: {
        name: "CALENDARIA.Calendar.rainbowlands.Weeks.4",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Weeks.4Short",
        weekNumber: 4,
      },
      lYDfmr6XhUgcXN4D: {
        name: "CALENDARIA.Calendar.rainbowlands.Weeks.5",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Weeks.5Short",
        weekNumber: 5,
      },
      jkNBkUCJK6uO8P3S: {
        name: "CALENDARIA.Calendar.rainbowlands.Weeks.6",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Weeks.6Short",
        weekNumber: 6,
      },
      TGgs2450ky14JUtM: {
        name: "CALENDARIA.Calendar.rainbowlands.Weeks.7",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Weeks.7Short",
        weekNumber: 7,
      },
      tNJf8D27MUoOsptp: {
        name: "CALENDARIA.Calendar.rainbowlands.Weeks.8",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Weeks.8Short",
        weekNumber: 8,
      },
      CE4YEFoPDRH7legY: {
        name: "CALENDARIA.Calendar.rainbowlands.Weeks.9",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Weeks.9Short",
        weekNumber: 9,
      },
      pjyDzSfPH90Ox5lz: {
        name: "CALENDARIA.Calendar.rainbowlands.Weeks.10",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Weeks.10Short",
        weekNumber: 10,
      },
      cOA9XBEqDSrd5MPh: {
        name: "CALENDARIA.Calendar.rainbowlands.Weeks.11",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Weeks.11Short",
        weekNumber: 11,
      },
      "2k6rzDSpLq8DVY41": {
        name: "CALENDARIA.Calendar.rainbowlands.Weeks.12",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Weeks.12Short",
        weekNumber: 12,
      },
      bHBcdbQEK9rfg6BK: {
        name: "CALENDARIA.Calendar.rainbowlands.Weeks.13",
        abbreviation: "CALENDARIA.Calendar.rainbowlands.Weeks.13Short",
        weekNumber: 13,
      },
    },
  },
  amPmNotation: {
    am: "AM",
    pm: "PM",
    amAbbr: "AM",
    pmAbbr: "PM",
  },
  dateFormats: {
    short: "{{EE}}, {{MMM}} {{DD}}",
    long: "{{EEEE}}, {{MMMM}} {{DD}}, {{YY}}",
    full: "{{EEEE}}, {{MMMM}} {{DD}}, {{YYYY}}",
    time: "{{H}}:{{M}}",
    time12: "{{h}}:{{M}} {{p}}",
    weekHeader: "[namedWeek] {{QQQQ}}",
    yearHeader: "Y",
    yearLabel: "YYYY",
  },
  metadata: {
    id: "rainbowlands",
    description: "CALENDARIA.Calendar.rainbowlands.Description",
    author: "Luber",
    system: "sdm",
    exportedFrom: "calendaria",
    exportedAt: 1775902199962,
    version: "1.0.4",
  },
  weather: {
    activeZone: "temperate",
    zones: {},
  },
  leapYearConfig: null,
  daylight: {
    enabled: false,
    shortestDay: 8,
    longestDay: 16,
    winterSolstice: 0,
    summerSolstice: 182,
  },
  currentDate: {
    year: 1,
    month: 0,
    day: 1,
    dayOfMonth: 1,
    hour: 12,
    minute: 0,
  },
  cycleFormat: "",
};
